# Generated by Django 4.2 on 2024-09-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_tasklist_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='manager',
            new_name='manage',
        ),
    ]
